### ISSUE TITLE
Installing in general Julia environment.

### ISSUE THREAD

**Issue by ll7** [sisl/AutonomousRiskFramework.jl#23]
From my experience, the `julia install.jl` script installs all packages in the standard julia environment. Is this an intentional design choice, or did I do something wrong during the installation?

**Comment by mossr** [comment]
This is intentional, but (partially) temporary.

1. Because the CARLA integration work is on-going, certain packages are installed in the standard Julia environment (e.g., those packages that I directly `Pkg.add` at the bottom of `install.jl`.
2. But, in order for the `AutonomousRiskFramework` package to correctly be installed, the local packages listed in the `packages` array need to be added before `AutonomousRiskFramework`. This is because those local packages are not part of the Julia Registry.
